server {
  listen 80;

  # Static file cache
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    root /usr/share/nginx/html;
    expires 30d;
    add_header Cache-Control "public, immutable";
    access_log off;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri /index.html =404;

    # Cache HTML for a short time to allow updates
    add_header Cache-Control "no-cache";
  }

  include /etc/nginx/extra-conf.d/*.conf;
}
