// This file is auto-generated by @hey-api/openapi-ts

export const TestRecordUpdateRequestSchema = {
    type: 'object',
    properties: {
        questions: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {
                    type: 'object'
                }
            }
        },
        answers: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {
                    type: 'object'
                }
            }
        },
        test_name: {
            type: 'string'
        },
        user_topic: {
            type: 'string'
        },
        total_score: {
            type: 'integer',
            format: 'int32'
        },
        total_max: {
            type: 'integer',
            format: 'int32'
        },
        result_description: {
            type: 'string'
        },
        scoring_ranges: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {
                    type: 'object'
                }
            }
        },
        conversation_id: {
            type: 'string'
        }
    }
} as const;

export const TestRecordResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        questions: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {
                    type: 'object'
                }
            }
        },
        answers: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {
                    type: 'object'
                }
            }
        },
        owner: {
            '$ref': '#/components/schemas/UserResponse'
        },
        test_name: {
            type: 'string'
        },
        user_topic: {
            type: 'string'
        },
        total_score: {
            type: 'integer',
            format: 'int32'
        },
        total_max: {
            type: 'integer',
            format: 'int32'
        },
        result_description: {
            type: 'string'
        },
        scoring_ranges: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {
                    type: 'object'
                }
            }
        },
        conversation_id: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const UserResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string'
        },
        is_active: {
            type: 'boolean'
        },
        is_superuser: {
            type: 'boolean'
        },
        full_name: {
            type: 'string'
        },
        streak_days: {
            type: 'integer',
            format: 'int32'
        },
        last_active_date: {
            type: 'string',
            format: 'date-time'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const UserRegisterRequestSchema = {
    required: ['email', 'password'],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            maxLength: 2147483647,
            minLength: 8,
            type: 'string'
        },
        full_name: {
            type: 'string'
        }
    }
} as const;

export const UserCreateRequestSchema = {
    required: ['email', 'password'],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            maxLength: 2147483647,
            minLength: 8,
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        is_active: {
            type: 'boolean'
        },
        is_superuser: {
            type: 'boolean'
        }
    }
} as const;

export const TestRecordCreateRequestSchema = {
    required: ['answers', 'questions', 'test_name'],
    type: 'object',
    properties: {
        questions: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {
                    type: 'object'
                }
            }
        },
        answers: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {
                    type: 'object'
                }
            }
        },
        test_name: {
            type: 'string'
        },
        user_topic: {
            type: 'string'
        },
        total_score: {
            type: 'integer',
            format: 'int32'
        },
        total_max: {
            type: 'integer',
            format: 'int32'
        },
        result_description: {
            type: 'string'
        },
        scoring_ranges: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: {
                    type: 'object'
                }
            }
        },
        conversation_id: {
            type: 'string'
        }
    }
} as const;

export const PasswordResetRequestSchema = {
    required: ['newPassword', 'token'],
    type: 'object',
    properties: {
        token: {
            type: 'string'
        },
        newPassword: {
            maxLength: 2147483647,
            minLength: 8,
            type: 'string'
        }
    }
} as const;

export const MessageResponseSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;

export const LoginRequestSchema = {
    required: ['password', 'username'],
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const TokenResponseSchema = {
    type: 'object',
    properties: {
        access_token: {
            type: 'string'
        },
        token_type: {
            type: 'string'
        }
    }
} as const;

export const AnalysisReportCreateRequestSchema = {
    required: ['analysis_result', 'file_name', 'file_type'],
    type: 'object',
    properties: {
        file_name: {
            type: 'string'
        },
        file_type: {
            type: 'string'
        },
        file_size: {
            type: 'integer',
            format: 'int32'
        },
        analysis_result: {
            type: 'string'
        },
        conversation_id: {
            type: 'string'
        }
    }
} as const;

export const AnalysisReportResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        owner: {
            '$ref': '#/components/schemas/UserResponse'
        },
        file_name: {
            type: 'string'
        },
        file_type: {
            type: 'string'
        },
        file_size: {
            type: 'integer',
            format: 'int32'
        },
        analysis_result: {
            type: 'string'
        },
        conversation_id: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const UserUpdateRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        },
        is_active: {
            type: 'boolean'
        },
        is_superuser: {
            type: 'boolean'
        }
    }
} as const;

export const UserUpdateMeRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        full_name: {
            type: 'string'
        }
    }
} as const;

export const UpdatePasswordRequestSchema = {
    required: ['currentPassword', 'newPassword'],
    type: 'object',
    properties: {
        currentPassword: {
            type: 'string'
        },
        newPassword: {
            maxLength: 2147483647,
            minLength: 8,
            type: 'string'
        }
    }
} as const;

export const PageableSchema = {
    type: 'object',
    properties: {
        page: {
            minimum: 0,
            type: 'integer',
            format: 'int32'
        },
        size: {
            minimum: 1,
            type: 'integer',
            format: 'int32'
        },
        sort: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const PageResponseUserResponseSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UserResponse'
            }
        },
        count: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const PageResponseTestRecordResponseSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TestRecordResponse'
            }
        },
        count: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const PageResponseAnalysisReportResponseSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/AnalysisReportResponse'
            }
        },
        count: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const AdminStatsResponseSchema = {
    type: 'object',
    properties: {
        total_users: {
            type: 'integer',
            format: 'int64'
        },
        total_test_records: {
            type: 'integer',
            format: 'int64'
        },
        total_analysis_reports: {
            type: 'integer',
            format: 'int64'
        },
        today_new_users: {
            type: 'integer',
            format: 'int64'
        },
        today_new_test_records: {
            type: 'integer',
            format: 'int64'
        },
        today_new_analysis_reports: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;