// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetStatsResponse, GetReportsData, GetReportsResponse, CreateReportData, CreateReportResponse, GetReports1Data, GetReports1Response, CreateReport1Data, CreateReport1Response, GetReportData, GetReportResponse, DeleteReportData, DeleteReportResponse, ResetPasswordData, ResetPasswordResponse, RecoverPasswordData, RecoverPasswordResponse, TestTokenResponse, LoginData, LoginResponse, UploadFileData, UploadFileResponse, SendChatMessageData, SendChatMessageResponse, GetMessagesData, GetMessagesResponse, GetConversationsData, GetConversationsResponse, DeleteConversationData, DeleteConversationResponse, GetRecordData, GetRecordResponse, UpdateRecordData, UpdateRecordResponse, DeleteRecordData, DeleteRecordResponse, GetRecordsData, GetRecordsResponse, CreateRecordData, CreateRecordResponse, GetRecords1Data, GetRecords1Response, CreateRecord1Data, CreateRecord1Response, GetAllRecordsData, GetAllRecordsResponse, DeleteAnyRecordData, DeleteAnyRecordResponse, SignupData, SignupResponse, GetAllUsersData, GetAllUsersResponse, CreateUserData, CreateUserResponse, GetUserByIdData, GetUserByIdResponse, DeleteUserData, DeleteUserResponse, UpdateUserData, UpdateUserResponse, GetCurrentUserResponse, DeleteCurrentUserResponse, UpdateCurrentUserData, UpdateCurrentUserResponse, UpdatePasswordData, UpdatePasswordResponse, HealthCheckResponse } from './types.gen';

export class AdminService {
    /**
     * 获取平台统计数据
     * @returns AdminStatsResponse OK
     * @throws ApiError
     */
    public static getStats(): CancelablePromise<GetStatsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/stats'
        });
    }
}

export class AnalysisReportsService {
    /**
     * 获取当前用户的分析报告列表
     * @param data The data for the request.
     * @param data.pageable
     * @returns PageResponseAnalysisReportResponse OK
     * @throws ApiError
     */
    public static getReports(data: GetReportsData): CancelablePromise<GetReportsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/analysis/reports/',
            query: {
                pageable: data.pageable
            }
        });
    }
    
    /**
     * 创建新的分析报告
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AnalysisReportResponse OK
     * @throws ApiError
     */
    public static createReport(data: CreateReportData): CancelablePromise<CreateReportResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/analysis/reports/',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 获取当前用户的分析报告列表
     * @param data The data for the request.
     * @param data.pageable
     * @returns PageResponseAnalysisReportResponse OK
     * @throws ApiError
     */
    public static getReports1(data: GetReports1Data): CancelablePromise<GetReports1Response> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/analysis/reports',
            query: {
                pageable: data.pageable
            }
        });
    }
    
    /**
     * 创建新的分析报告
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AnalysisReportResponse OK
     * @throws ApiError
     */
    public static createReport1(data: CreateReport1Data): CancelablePromise<CreateReport1Response> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/analysis/reports',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 获取指定分析报告的详情
     * @param data The data for the request.
     * @param data.id
     * @returns AnalysisReportResponse OK
     * @throws ApiError
     */
    public static getReport(data: GetReportData): CancelablePromise<GetReportResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/analysis/reports/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * 删除指定的分析报告
     * @param data The data for the request.
     * @param data.id
     * @returns MessageResponse OK
     * @throws ApiError
     */
    public static deleteReport(data: DeleteReportData): CancelablePromise<DeleteReportResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/analysis/reports/{id}',
            path: {
                id: data.id
            }
        });
    }
}

export class AuthenticationService {
    /**
     * 使用令牌重置密码
     * @param data The data for the request.
     * @param data.requestBody
     * @returns MessageResponse OK
     * @throws ApiError
     */
    public static resetPassword(data: ResetPasswordData): CancelablePromise<ResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 发送密码找回邮件
     * @param data The data for the request.
     * @param data.email
     * @returns MessageResponse OK
     * @throws ApiError
     */
    public static recoverPassword(data: RecoverPasswordData): CancelablePromise<RecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            }
        });
    }
    
    /**
     * 验证当前 JWT 令牌是否有效
     * @returns UserResponse OK
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<TestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * 用户登录，返回 JWT 访问令牌
     * @param data The data for the request.
     * @param data.request
     * @returns TokenResponse OK
     * @throws ApiError
     */
    public static login(data: LoginData): CancelablePromise<LoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            body: data.request,
            mediaType: 'application/json'
        });
    }
}

export class DifyAiService {
    /**
     * 上传文件到 Dify
     * @param data The data for the request.
     * @param data.apiKeyName
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static uploadFile(data: UploadFileData): CancelablePromise<UploadFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/dify/files/upload',
            query: {
                api_key_name: data.apiKeyName
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 发送聊天消息，返回 SSE 流式响应
     * @param data The data for the request.
     * @param data.apiKeyName
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static sendChatMessage(data: SendChatMessageData): CancelablePromise<SendChatMessageResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/dify/chat-messages',
            query: {
                api_key_name: data.apiKeyName
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 获取指定对话的消息历史（管理员可查看指定用户的会话）
     * @param data The data for the request.
     * @param data.apiKeyName
     * @param data.conversationId
     * @param data.user
     * @returns unknown OK
     * @throws ApiError
     */
    public static getMessages(data: GetMessagesData): CancelablePromise<GetMessagesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/dify/messages',
            query: {
                api_key_name: data.apiKeyName,
                conversation_id: data.conversationId,
                user: data.user
            }
        });
    }
    
    /**
     * 获取用户的对话列表（管理员可查看指定用户的会话）
     * @param data The data for the request.
     * @param data.apiKeyName
     * @param data.user
     * @returns unknown OK
     * @throws ApiError
     */
    public static getConversations(data: GetConversationsData): CancelablePromise<GetConversationsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/dify/conversations',
            query: {
                api_key_name: data.apiKeyName,
                user: data.user
            }
        });
    }
    
    /**
     * 删除指定对话（管理员可删除指定用户的会话）
     * @param data The data for the request.
     * @param data.id
     * @param data.apiKeyName
     * @param data.user
     * @returns MessageResponse OK
     * @throws ApiError
     */
    public static deleteConversation(data: DeleteConversationData): CancelablePromise<DeleteConversationResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/dify/conversations/{id}',
            path: {
                id: data.id
            },
            query: {
                api_key_name: data.apiKeyName,
                user: data.user
            }
        });
    }
}

export class TestRecordsService {
    /**
     * 获取指定测评记录的详情
     * @param data The data for the request.
     * @param data.id
     * @returns TestRecordResponse OK
     * @throws ApiError
     */
    public static getRecord(data: GetRecordData): CancelablePromise<GetRecordResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/test-records/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * 更新指定的测评记录
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns TestRecordResponse OK
     * @throws ApiError
     */
    public static updateRecord(data: UpdateRecordData): CancelablePromise<UpdateRecordResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/test-records/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 删除指定的测评记录
     * @param data The data for the request.
     * @param data.id
     * @returns MessageResponse OK
     * @throws ApiError
     */
    public static deleteRecord(data: DeleteRecordData): CancelablePromise<DeleteRecordResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/test-records/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * 获取当前用户的测评记录列表
     * @param data The data for the request.
     * @param data.pageable
     * @returns PageResponseTestRecordResponse OK
     * @throws ApiError
     */
    public static getRecords(data: GetRecordsData): CancelablePromise<GetRecordsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/test-records/',
            query: {
                pageable: data.pageable
            }
        });
    }
    
    /**
     * 创建新的测评记录
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TestRecordResponse OK
     * @throws ApiError
     */
    public static createRecord(data: CreateRecordData): CancelablePromise<CreateRecordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/test-records/',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 获取当前用户的测评记录列表
     * @param data The data for the request.
     * @param data.pageable
     * @returns PageResponseTestRecordResponse OK
     * @throws ApiError
     */
    public static getRecords1(data: GetRecords1Data): CancelablePromise<GetRecords1Response> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/test-records',
            query: {
                pageable: data.pageable
            }
        });
    }
    
    /**
     * 创建新的测评记录
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TestRecordResponse OK
     * @throws ApiError
     */
    public static createRecord1(data: CreateRecord1Data): CancelablePromise<CreateRecord1Response> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/test-records',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 管理员获取所有测评记录（可筛选用户）
     * @param data The data for the request.
     * @param data.pageable
     * @param data.userId
     * @returns PageResponseTestRecordResponse OK
     * @throws ApiError
     */
    public static getAllRecords(data: GetAllRecordsData): CancelablePromise<GetAllRecordsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/test-records',
            query: {
                userId: data.userId,
                pageable: data.pageable
            }
        });
    }
    
    /**
     * 管理员删除任意测评记录
     * @param data The data for the request.
     * @param data.id
     * @returns MessageResponse OK
     * @throws ApiError
     */
    public static deleteAnyRecord(data: DeleteAnyRecordData): CancelablePromise<DeleteAnyRecordResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/admin/test-records/{id}',
            path: {
                id: data.id
            }
        });
    }
}

export class UsersService {
    /**
     * 用户注册
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserResponse OK
     * @throws ApiError
     */
    public static signup(data: SignupData): CancelablePromise<SignupResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 管理员获取所有用户列表
     * @param data The data for the request.
     * @param data.pageable
     * @returns PageResponseUserResponse OK
     * @throws ApiError
     */
    public static getAllUsers(data: GetAllUsersData): CancelablePromise<GetAllUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                pageable: data.pageable
            }
        });
    }
    
    /**
     * 管理员创建新用户
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserResponse OK
     * @throws ApiError
     */
    public static createUser(data: CreateUserData): CancelablePromise<CreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 管理员获取指定用户信息
     * @param data The data for the request.
     * @param data.id
     * @returns UserResponse OK
     * @throws ApiError
     */
    public static getUserById(data: GetUserByIdData): CancelablePromise<GetUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * 管理员删除指定用户
     * @param data The data for the request.
     * @param data.id
     * @returns MessageResponse OK
     * @throws ApiError
     */
    public static deleteUser(data: DeleteUserData): CancelablePromise<DeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{id}',
            path: {
                id: data.id
            }
        });
    }
    
    /**
     * 管理员更新指定用户信息
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns UserResponse OK
     * @throws ApiError
     */
    public static updateUser(data: UpdateUserData): CancelablePromise<UpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 获取当前登录用户信息
     * @returns UserResponse OK
     * @throws ApiError
     */
    public static getCurrentUser(): CancelablePromise<GetCurrentUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * 删除当前登录用户账号
     * @returns MessageResponse OK
     * @throws ApiError
     */
    public static deleteCurrentUser(): CancelablePromise<DeleteCurrentUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * 更新当前登录用户信息
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserResponse OK
     * @throws ApiError
     */
    public static updateCurrentUser(data: UpdateCurrentUserData): CancelablePromise<UpdateCurrentUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * 修改当前用户密码
     * @param data The data for the request.
     * @param data.requestBody
     * @returns MessageResponse OK
     * @throws ApiError
     */
    public static updatePassword(data: UpdatePasswordData): CancelablePromise<UpdatePasswordResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class UtilsService {
    /**
     * 健康检查
     * @returns string OK
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<HealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}