// This file is auto-generated by @hey-api/openapi-ts

export type AdminStatsResponse = {
    total_users?: number;
    total_test_records?: number;
    total_analysis_reports?: number;
    today_new_users?: number;
    today_new_test_records?: number;
    today_new_analysis_reports?: number;
};

export type AnalysisReportCreateRequest = {
    file_name: string;
    file_type: string;
    file_size?: number;
    analysis_result: string;
    conversation_id?: string;
};

export type AnalysisReportResponse = {
    id?: string;
    owner?: UserResponse;
    file_name?: string;
    file_type?: string;
    file_size?: number;
    analysis_result?: string;
    conversation_id?: string;
    created_at?: string;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type MessageResponse = {
    message?: string;
};

export type Pageable = {
    page?: number;
    size?: number;
    sort?: Array<(string)>;
};

export type PageResponseAnalysisReportResponse = {
    data?: Array<AnalysisReportResponse>;
    count?: number;
};

export type PageResponseTestRecordResponse = {
    data?: Array<TestRecordResponse>;
    count?: number;
};

export type PageResponseUserResponse = {
    data?: Array<UserResponse>;
    count?: number;
};

export type PasswordResetRequest = {
    token: string;
    newPassword: string;
};

export type TestRecordCreateRequest = {
    questions: Array<{
        [key: string]: {
            [key: string]: unknown;
        };
    }>;
    answers: Array<{
        [key: string]: {
            [key: string]: unknown;
        };
    }>;
    test_name: string;
    user_topic?: string;
    total_score?: number;
    total_max?: number;
    result_description?: string;
    scoring_ranges?: Array<{
        [key: string]: {
            [key: string]: unknown;
        };
    }>;
    conversation_id?: string;
};

export type TestRecordResponse = {
    id?: string;
    questions?: Array<{
        [key: string]: {
            [key: string]: unknown;
        };
    }>;
    answers?: Array<{
        [key: string]: {
            [key: string]: unknown;
        };
    }>;
    owner?: UserResponse;
    test_name?: string;
    user_topic?: string;
    total_score?: number;
    total_max?: number;
    result_description?: string;
    scoring_ranges?: Array<{
        [key: string]: {
            [key: string]: unknown;
        };
    }>;
    conversation_id?: string;
    created_at?: string;
};

export type TestRecordUpdateRequest = {
    questions?: Array<{
        [key: string]: {
            [key: string]: unknown;
        };
    }>;
    answers?: Array<{
        [key: string]: {
            [key: string]: unknown;
        };
    }>;
    test_name?: string;
    user_topic?: string;
    total_score?: number;
    total_max?: number;
    result_description?: string;
    scoring_ranges?: Array<{
        [key: string]: {
            [key: string]: unknown;
        };
    }>;
    conversation_id?: string;
};

export type TokenResponse = {
    access_token?: string;
    token_type?: string;
};

export type UpdatePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type UserCreateRequest = {
    email: string;
    password: string;
    full_name?: string;
    is_active?: boolean;
    is_superuser?: boolean;
};

export type UserRegisterRequest = {
    email: string;
    password: string;
    full_name?: string;
};

export type UserResponse = {
    id?: string;
    email?: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: string;
    streak_days?: number;
    last_active_date?: string;
    created_at?: string;
};

export type UserUpdateMeRequest = {
    email?: string;
    full_name?: string;
};

export type UserUpdateRequest = {
    email?: string;
    password?: string;
    full_name?: string;
    is_active?: boolean;
    is_superuser?: boolean;
};

export type GetStatsResponse = (AdminStatsResponse);

export type GetReportsData = {
    pageable: Pageable;
};

export type GetReportsResponse = (PageResponseAnalysisReportResponse);

export type CreateReportData = {
    requestBody: AnalysisReportCreateRequest;
};

export type CreateReportResponse = (AnalysisReportResponse);

export type GetReports1Data = {
    pageable: Pageable;
};

export type GetReports1Response = (PageResponseAnalysisReportResponse);

export type CreateReport1Data = {
    requestBody: AnalysisReportCreateRequest;
};

export type CreateReport1Response = (AnalysisReportResponse);

export type GetReportData = {
    id: string;
};

export type GetReportResponse = (AnalysisReportResponse);

export type DeleteReportData = {
    id: string;
};

export type DeleteReportResponse = (MessageResponse);

export type ResetPasswordData = {
    requestBody: PasswordResetRequest;
};

export type ResetPasswordResponse = (MessageResponse);

export type RecoverPasswordData = {
    email: string;
};

export type RecoverPasswordResponse = (MessageResponse);

export type TestTokenResponse = (UserResponse);

export type LoginData = {
    request: LoginRequest;
};

export type LoginResponse = (TokenResponse);

export type UploadFileData = {
    apiKeyName: string;
    requestBody: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type UploadFileResponse = ({
    [key: string]: {
        [key: string]: unknown;
    };
});

export type SendChatMessageData = {
    apiKeyName: string;
    requestBody: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type SendChatMessageResponse = (unknown);

export type GetMessagesData = {
    apiKeyName: string;
    conversationId: string;
    user?: string;
};

export type GetMessagesResponse = ({
    [key: string]: {
        [key: string]: unknown;
    };
});

export type GetConversationsData = {
    apiKeyName: string;
    user?: string;
};

export type GetConversationsResponse = ({
    [key: string]: {
        [key: string]: unknown;
    };
});

export type DeleteConversationData = {
    apiKeyName: string;
    id: string;
    user?: string;
};

export type DeleteConversationResponse = (MessageResponse);

export type GetRecordData = {
    id: string;
};

export type GetRecordResponse = (TestRecordResponse);

export type UpdateRecordData = {
    id: string;
    requestBody: TestRecordUpdateRequest;
};

export type UpdateRecordResponse = (TestRecordResponse);

export type DeleteRecordData = {
    id: string;
};

export type DeleteRecordResponse = (MessageResponse);

export type GetRecordsData = {
    pageable: Pageable;
};

export type GetRecordsResponse = (PageResponseTestRecordResponse);

export type CreateRecordData = {
    requestBody: TestRecordCreateRequest;
};

export type CreateRecordResponse = (TestRecordResponse);

export type GetRecords1Data = {
    pageable: Pageable;
};

export type GetRecords1Response = (PageResponseTestRecordResponse);

export type CreateRecord1Data = {
    requestBody: TestRecordCreateRequest;
};

export type CreateRecord1Response = (TestRecordResponse);

export type GetAllRecordsData = {
    pageable: Pageable;
    userId?: string;
};

export type GetAllRecordsResponse = (PageResponseTestRecordResponse);

export type DeleteAnyRecordData = {
    id: string;
};

export type DeleteAnyRecordResponse = (MessageResponse);

export type SignupData = {
    requestBody: UserRegisterRequest;
};

export type SignupResponse = (UserResponse);

export type GetAllUsersData = {
    pageable: Pageable;
};

export type GetAllUsersResponse = (PageResponseUserResponse);

export type CreateUserData = {
    requestBody: UserCreateRequest;
};

export type CreateUserResponse = (UserResponse);

export type GetUserByIdData = {
    id: string;
};

export type GetUserByIdResponse = (UserResponse);

export type DeleteUserData = {
    id: string;
};

export type DeleteUserResponse = (MessageResponse);

export type UpdateUserData = {
    id: string;
    requestBody: UserUpdateRequest;
};

export type UpdateUserResponse = (UserResponse);

export type GetCurrentUserResponse = (UserResponse);

export type DeleteCurrentUserResponse = (MessageResponse);

export type UpdateCurrentUserData = {
    requestBody: UserUpdateMeRequest;
};

export type UpdateCurrentUserResponse = (UserResponse);

export type UpdatePasswordData = {
    requestBody: UpdatePasswordRequest;
};

export type UpdatePasswordResponse = (MessageResponse);

export type HealthCheckResponse = ({
    [key: string]: (string);
});