// This file is auto-generated by @hey-api/openapi-ts

export type AdminStatsResponse = {
    total_users: number;
    total_test_records: number;
    total_analysis_reports: number;
    today_new_users: number;
    today_new_test_records: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessageRequest = {
    inputs?: {
        [key: string]: unknown;
    };
    query: string;
    response_mode?: string;
    conversation_id?: string;
    user: string;
    auto_generate_name?: boolean;
    files?: Array<{
        [key: string]: unknown;
    }>;
};

export type FileAnalysisReportCreate = {
    file_name: string;
    file_type: string;
    file_size?: (number | null);
    analysis_result: string;
    conversation_id?: (string | null);
};

export type FileAnalysisReportPublic = {
    file_name: string;
    file_type: string;
    file_size?: (number | null);
    analysis_result: string;
    conversation_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type FileAnalysisReportsPublic = {
    data: Array<FileAnalysisReportPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TestRecordCreate = {
    test_name: string;
    user_topic?: (string | null);
    total_score?: (number | null);
    total_max?: (number | null);
    result_description?: (string | null);
    questions?: Array<unknown>;
    answers?: Array<unknown>;
    scoring_ranges?: Array<unknown>;
    conversation_id?: (string | null);
};

export type TestRecordPublic = {
    test_name: string;
    user_topic?: (string | null);
    total_score?: (number | null);
    total_max?: (number | null);
    result_description?: (string | null);
    questions?: Array<unknown>;
    answers?: Array<unknown>;
    scoring_ranges?: Array<unknown>;
    conversation_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type TestRecordsPublic = {
    data: Array<TestRecordPublic>;
    count: number;
};

export type TestRecordUpdate = {
    test_name?: (string | null);
    user_topic?: (string | null);
    total_score?: (number | null);
    total_max?: (number | null);
    result_description?: (string | null);
    scoring_ranges?: (Array<unknown> | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UploadFileRequest = {
    file_name: string;
    file_data: string;
    user: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminReadAdminTestRecordsData = {
    limit?: number;
    skip?: number;
    userId?: (string | null);
};

export type AdminReadAdminTestRecordsResponse = (unknown);

export type AdminDeleteAdminTestRecordData = {
    id: string;
};

export type AdminDeleteAdminTestRecordResponse = (unknown);

export type AdminGetAdminStatsResponse = (AdminStatsResponse);

export type AnalysisReadAnalysisReportsData = {
    limit?: number;
    skip?: number;
};

export type AnalysisReadAnalysisReportsResponse = (FileAnalysisReportsPublic);

export type AnalysisCreateAnalysisReportData = {
    requestBody: FileAnalysisReportCreate;
};

export type AnalysisCreateAnalysisReportResponse = (FileAnalysisReportPublic);

export type AnalysisReadAnalysisReportData = {
    reportId: string;
};

export type AnalysisReadAnalysisReportResponse = (FileAnalysisReportPublic);

export type AnalysisDeleteAnalysisReportData = {
    reportId: string;
};

export type AnalysisDeleteAnalysisReportResponse = (Message);

export type DifySendChatMessageData = {
    apiKeyName?: (string | null);
    requestBody: ChatMessageRequest;
};

export type DifySendChatMessageResponse = (unknown);

export type DifyUploadFileData = {
    apiKeyName?: (string | null);
    requestBody: UploadFileRequest;
};

export type DifyUploadFileResponse = (unknown);

export type DifyGetConversationsData = {
    apiKeyName?: (string | null);
    lastId?: (string | null);
    limit?: number;
};

export type DifyGetConversationsResponse = (unknown);

export type DifyGetMessagesData = {
    apiKeyName?: (string | null);
    conversationId: string;
    firstId?: (string | null);
    limit?: number;
};

export type DifyGetMessagesResponse = (unknown);

export type DifyDeleteConversationData = {
    apiKeyName?: (string | null);
    conversationId: string;
};

export type DifyDeleteConversationResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TestRecordsReadTestRecordsData = {
    limit?: number;
    skip?: number;
};

export type TestRecordsReadTestRecordsResponse = (TestRecordsPublic);

export type TestRecordsCreateTestRecordData = {
    requestBody: TestRecordCreate;
};

export type TestRecordsCreateTestRecordResponse = (TestRecordPublic);

export type TestRecordsReadTestRecordData = {
    id: string;
};

export type TestRecordsReadTestRecordResponse = (TestRecordPublic);

export type TestRecordsUpdateTestRecordData = {
    id: string;
    requestBody: TestRecordUpdate;
};

export type TestRecordsUpdateTestRecordResponse = (TestRecordPublic);

export type TestRecordsDeleteTestRecordData = {
    id: string;
};

export type TestRecordsDeleteTestRecordResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);