/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminLayoutRouteImport } from './routes/_admin-layout'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as UserTestRouteImport } from './routes/user/test'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as UserAiDoctorRouteImport } from './routes/user/ai-doctor'
import { Route as LayoutPsychologicalTestRouteImport } from './routes/_layout/psychological-test'
import { Route as AdminLayoutUserManageRouteImport } from './routes/_admin-layout/user-manage'
import { Route as AdminLayoutChatHistoryRouteImport } from './routes/_admin-layout/chat-history'
import { Route as AdminLayoutAdminSettingsRouteImport } from './routes/_admin-layout/admin-settings'
import { Route as AdminLayoutAdminRouteImport } from './routes/_admin-layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_admin-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserTestRoute = UserTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAiDoctorRoute = UserAiDoctorRouteImport.update({
  id: '/ai-doctor',
  path: '/ai-doctor',
  getParentRoute: () => UserRouteRoute,
} as any)
const LayoutPsychologicalTestRoute = LayoutPsychologicalTestRouteImport.update({
  id: '/_layout/psychological-test',
  path: '/psychological-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutUserManageRoute = AdminLayoutUserManageRouteImport.update({
  id: '/user-manage',
  path: '/user-manage',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutChatHistoryRoute = AdminLayoutChatHistoryRouteImport.update({
  id: '/chat-history',
  path: '/chat-history',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAdminSettingsRoute =
  AdminLayoutAdminSettingsRouteImport.update({
    id: '/admin-settings',
    path: '/admin-settings',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAdminRoute = AdminLayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminLayoutAdminRoute
  '/admin-settings': typeof AdminLayoutAdminSettingsRoute
  '/chat-history': typeof AdminLayoutChatHistoryRoute
  '/user-manage': typeof AdminLayoutUserManageRoute
  '/psychological-test': typeof LayoutPsychologicalTestRoute
  '/user/ai-doctor': typeof UserAiDoctorRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/test': typeof UserTestRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminLayoutAdminRoute
  '/admin-settings': typeof AdminLayoutAdminSettingsRoute
  '/chat-history': typeof AdminLayoutChatHistoryRoute
  '/user-manage': typeof AdminLayoutUserManageRoute
  '/psychological-test': typeof LayoutPsychologicalTestRoute
  '/user/ai-doctor': typeof UserAiDoctorRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/test': typeof UserTestRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/_admin-layout': typeof AdminLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_admin-layout/admin': typeof AdminLayoutAdminRoute
  '/_admin-layout/admin-settings': typeof AdminLayoutAdminSettingsRoute
  '/_admin-layout/chat-history': typeof AdminLayoutChatHistoryRoute
  '/_admin-layout/user-manage': typeof AdminLayoutUserManageRoute
  '/_layout/psychological-test': typeof LayoutPsychologicalTestRoute
  '/user/ai-doctor': typeof UserAiDoctorRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/test': typeof UserTestRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin-settings'
    | '/chat-history'
    | '/user-manage'
    | '/psychological-test'
    | '/user/ai-doctor'
    | '/user/settings'
    | '/user/test'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin-settings'
    | '/chat-history'
    | '/user-manage'
    | '/psychological-test'
    | '/user/ai-doctor'
    | '/user/settings'
    | '/user/test'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/user'
    | '/_admin-layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_admin-layout/admin'
    | '/_admin-layout/admin-settings'
    | '/_admin-layout/chat-history'
    | '/_admin-layout/user-manage'
    | '/_layout/psychological-test'
    | '/user/ai-doctor'
    | '/user/settings'
    | '/user/test'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  LayoutPsychologicalTestRoute: typeof LayoutPsychologicalTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin-layout': {
      id: '/_admin-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/test': {
      id: '/user/test'
      path: '/test'
      fullPath: '/user/test'
      preLoaderRoute: typeof UserTestRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/ai-doctor': {
      id: '/user/ai-doctor'
      path: '/ai-doctor'
      fullPath: '/user/ai-doctor'
      preLoaderRoute: typeof UserAiDoctorRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_layout/psychological-test': {
      id: '/_layout/psychological-test'
      path: '/psychological-test'
      fullPath: '/psychological-test'
      preLoaderRoute: typeof LayoutPsychologicalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin-layout/user-manage': {
      id: '/_admin-layout/user-manage'
      path: '/user-manage'
      fullPath: '/user-manage'
      preLoaderRoute: typeof AdminLayoutUserManageRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_admin-layout/chat-history': {
      id: '/_admin-layout/chat-history'
      path: '/chat-history'
      fullPath: '/chat-history'
      preLoaderRoute: typeof AdminLayoutChatHistoryRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_admin-layout/admin-settings': {
      id: '/_admin-layout/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminLayoutAdminSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_admin-layout/admin': {
      id: '/_admin-layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutAdminRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface UserRouteRouteChildren {
  UserAiDoctorRoute: typeof UserAiDoctorRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserTestRoute: typeof UserTestRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserAiDoctorRoute: UserAiDoctorRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserTestRoute: UserTestRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminLayoutAdminRoute: typeof AdminLayoutAdminRoute
  AdminLayoutAdminSettingsRoute: typeof AdminLayoutAdminSettingsRoute
  AdminLayoutChatHistoryRoute: typeof AdminLayoutChatHistoryRoute
  AdminLayoutUserManageRoute: typeof AdminLayoutUserManageRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAdminRoute: AdminLayoutAdminRoute,
  AdminLayoutAdminSettingsRoute: AdminLayoutAdminSettingsRoute,
  AdminLayoutChatHistoryRoute: AdminLayoutChatHistoryRoute,
  AdminLayoutUserManageRoute: AdminLayoutUserManageRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRouteRoute: UserRouteRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  LayoutPsychologicalTestRoute: LayoutPsychologicalTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
